# Generated by Django 5.2.7 on 2025-11-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='updated_at',
        ),
    ]
